version: '3.1'

services:
  db:
    image: mariadb:10.3.32
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_USER: tkad06
      MARIADB_DATABASE: alushop
      MARIADB_PASSWORD: alushop
      MARIADB_ROOT_PASSWORD: alushoproot
    volumes:
      - ./volumes/mariadb:/var/lib/mysql
    ports:
      - 3306:3306